import { describe, it, expect } from 'vitest'
import { getCardCategory } from './cardCategory'

// Each case uses oracle/type-line text copied (approximately) from Scryfall so
// any future regression is obvious from the case name.
const cases = [
  // ── Counterspell ─────────────────────────────────────────────────────────
  ['Counterspell',
    'Counter target spell.',
    'Instant', 'Counterspell'],
  ['Negate (noncreature)',
    'Counter target noncreature spell.',
    'Instant', 'Counterspell'],
  ['Hydroblast (color-qualified counter)',
    'Choose one — Counter target red spell.; Destroy target red permanent.',
    'Instant', 'Counterspell'],
  ['Stifle (counter ability)',
    'Counter target activated or triggered ability.',
    'Instant', 'Counterspell'],

  // ── Board Wipe ───────────────────────────────────────────────────────────
  ['Wrath of God',
    'Destroy all creatures. They can\'t be regenerated.',
    'Sorcery', 'Board Wipe'],
  ['Cyclonic Rift overload phrasing — bounce single first',
    'Return target nonland permanent you don\'t control to its owner\'s hand. Overload {6}{U}',
    'Instant', 'Removal'],
  ['Pyroclasm (damage-each-creature wipe)',
    'Pyroclasm deals 2 damage to each creature.',
    'Sorcery', 'Board Wipe'],
  ['Toxic Deluge (-X/-X wipe)',
    'Pay X life. All creatures get -X/-X until end of turn.',
    'Sorcery', 'Board Wipe'],

  // ── Ramp ─────────────────────────────────────────────────────────────────
  ['Cultivate (basic-land tutor)',
    'Search your library for up to two basic land cards, reveal those cards, put one onto the battlefield tapped and the other into your hand, then shuffle.',
    'Sorcery', 'Ramp'],
  ['Rampant Growth',
    'Search your library for a basic land card, put it onto the battlefield tapped, then shuffle.',
    'Sorcery', 'Ramp'],
  ['Skyshroud Claim (typed land tutor)',
    'Search your library for two Forest cards, put them onto the battlefield, then shuffle.',
    'Sorcery', 'Ramp'],
  ['Wood Elves (Forest fetch creature)',
    'When Wood Elves enters the battlefield, search your library for a Forest card, put that card onto the battlefield, then shuffle.',
    'Creature — Elf Scout', 'Ramp'],
  ['Exploration (additional land)',
    'You may play an additional land on each of your turns.',
    'Enchantment', 'Ramp'],
  ['Azusa, Lost but Seeking',
    'You may play two additional lands on each of your turns.',
    'Legendary Creature — Human Monk', 'Ramp'],
  ['Dockside Extortionist (treasure ramp)',
    'When Dockside Extortionist enters the battlefield, create X Treasure tokens, where X is the number of artifacts and enchantments your opponents control.',
    'Legendary Creature — Goblin Pirate', 'Ramp'],
  ['Llanowar Elves (mana dork)',
    '{T}: Add {G}.',
    'Creature — Elf Druid', 'Ramp'],
  ['Birds of Paradise (any-color dork)',
    '{T}: Add one mana of any color.',
    'Creature — Bird', 'Ramp'],

  // ── Ramp (formerly Mana Rock — now folded into Ramp) ─────────────────────
  ['Sol Ring (mana rock as Ramp)',
    '{T}: Add {C}{C}.',
    'Artifact', 'Ramp'],
  ['Arcane Signet (mana rock as Ramp)',
    '{T}: Add one mana of any color in your commander\'s color identity.',
    'Artifact', 'Ramp'],
  ['Mind Stone (mana rock + draw → Ramp wins)',
    '{T}: Add {C}. {1}, {T}, Sacrifice Mind Stone: Draw a card.',
    'Artifact', 'Ramp'],

  // ── Tutor ────────────────────────────────────────────────────────────────
  ['Demonic Tutor',
    'Search your library for a card, put it into your hand, then shuffle.',
    'Sorcery', 'Tutor'],
  ['Worldly Tutor',
    'Search your library for a creature card, reveal it, then shuffle and put that card on top.',
    'Instant', 'Tutor'],
  ['Idyllic Tutor',
    'Search your library for an enchantment card, reveal it, put it into your hand, then shuffle.',
    'Sorcery', 'Tutor'],

  // ── Card Draw ────────────────────────────────────────────────────────────
  ['Brainstorm',
    'Draw three cards, then put two cards from your hand on top of your library in any order.',
    'Instant', 'Card Draw'],
  ["Sphinx's Revelation (draw X)",
    'You gain X life and draw X cards.',
    'Instant', 'Card Draw'],
  ['Blue Sun\'s Zenith (target draws X)',
    'Target player draws X cards. Shuffle Blue Sun\'s Zenith into its owner\'s library.',
    'Instant', 'Card Draw'],
  ['Wheel of Fortune (each player draws)',
    'Each player discards their hand, then draws seven cards.',
    'Sorcery', 'Card Draw'],
  ['Outpost Siege (impulse draw mode)',
    'At the beginning of your upkeep, exile the top card of your library. Until end of turn, you may play that card.',
    'Enchantment', 'Card Draw'],

  // ── Removal ──────────────────────────────────────────────────────────────
  ['Doom Blade (color-qualified removal)',
    'Destroy target nonblack creature.',
    'Instant', 'Removal'],
  ['Swords to Plowshares',
    'Exile target creature. Its controller gains life equal to its power.',
    'Instant', 'Removal'],
  ['Beast Within',
    'Destroy target permanent. Its controller creates a 3/3 green Beast creature token.',
    'Instant', 'Removal'],
  ['Boomerang (bounce)',
    'Return target permanent to its owner\'s hand.',
    'Instant', 'Removal'],
  ['Lightning Bolt (any target)',
    'Lightning Bolt deals 3 damage to any target.',
    'Instant', 'Removal'],

  // ── Burn ─────────────────────────────────────────────────────────────────
  ['Lava Spike',
    'Lava Spike deals 3 damage to target player or planeswalker.',
    'Sorcery', 'Burn'],

  // ── Tokens ───────────────────────────────────────────────────────────────
  ['Lingering Souls',
    'Create two 1/1 white and black Spirit creature tokens with flying. Flashback {1}{B}.',
    'Sorcery', 'Tokens'],

  // ── Graveyard ────────────────────────────────────────────────────────────
  ['Reanimate',
    'Put target creature card from a graveyard onto the battlefield under your control.',
    'Sorcery', 'Graveyard'],
  ['Animate Dead (return from graveyard)',
    'When Animate Dead enters the battlefield, return target creature card from a graveyard to the battlefield under your control attached to Animate Dead.',
    'Enchantment — Aura', 'Graveyard'],
  // Mill split out — see dedicated section below.

  // ── Protection ───────────────────────────────────────────────────────────
  ['Lightning Greaves',
    'Equipped creature has haste and shroud.',
    'Artifact — Equipment', 'Protection'],
  ['Heroic Intervention',
    'Permanents you control gain hexproof and indestructible until end of turn.',
    'Instant', 'Protection'],
  ['Asceticism (passive grant)',
    'Creatures you control have hexproof.',
    'Enchantment', 'Protection'],

  // ── Extra Turns ──────────────────────────────────────────────────────────
  ['Time Warp',
    'Take an extra turn after this one.',
    'Sorcery', 'Extra Turns'],

  // ── Combo / wincon ───────────────────────────────────────────────────────
  ['Thassa\'s Oracle (win the game)',
    'When Thassa\'s Oracle enters the battlefield, look at the top X cards of your library, where X is your devotion to blue. ... If you have no cards in your library, you win the game.',
    'Creature — Merfolk', 'Combo'],

  // ── Mill ─────────────────────────────────────────────────────────────────
  ['Glimpse the Unthinkable',
    'Target player puts the top ten cards of their library into their graveyard.',
    'Sorcery', 'Mill'],
  ['Mind Funeral',
    'Target opponent puts cards from the top of their library into their graveyard until four land cards are put into their graveyard this way.',
    'Sorcery', 'Mill'],

  // ── Drain ────────────────────────────────────────────────────────────────
  ['Exsanguinate',
    'Each opponent loses X life. You gain life equal to the life lost this way.',
    'Sorcery', 'Drain'],
  ['Tendrils of Agony',
    'Target opponent loses 2 life and you gain 2 life. Storm.',
    'Sorcery', 'Drain'],
  ['Blood Artist (death-trigger drain)',
    'Whenever Blood Artist or another creature dies, target player loses 1 life and you gain 1 life.',
    'Creature — Vampire', 'Drain'],

  // ── Discard (forced discard, not Wheel-style draw) ───────────────────────
  ['Mind Twist',
    'Target player discards X cards at random.',
    'Sorcery', 'Discard'],
  ['Hymn to Tourach',
    'Target player discards two cards at random.',
    'Sorcery', 'Discard'],
  ['Wheel of Fortune stays Card Draw',
    'Each player discards their hand, then draws seven cards.',
    'Sorcery', 'Card Draw'],

  // ── Cost Reduction ───────────────────────────────────────────────────────
  ['Goblin Warchief',
    'Goblin spells you cast cost {1} less to cast. Goblin creatures you control have haste.',
    'Creature — Goblin Warrior', 'Cost Reduction'],
  ['Urza\'s Incubator',
    'As Urza\'s Incubator enters the battlefield, choose a creature type. Creature spells of the chosen type cost {2} less to cast.',
    'Artifact', 'Cost Reduction'],
  ['Heartless Summoning',
    'Creature spells you cast cost {2} less to cast. Creatures you control get -1/-1.',
    'Enchantment', 'Cost Reduction'],

  // ── Stax ─────────────────────────────────────────────────────────────────
  ['Thalia, Guardian of Thraben',
    'First strike. Noncreature spells cost {1} more to cast.',
    'Legendary Creature — Human Soldier', 'Stax'],
  ['Trinisphere',
    'As long as Trinisphere is untapped, each spell that would cost less than three mana to cast costs three mana more to cast.',
    'Artifact', 'Stax'],
  ['Winter Orb',
    'Players can\'t untap more than one land during their untap steps.',
    'Artifact', 'Stax'],
  ['Blood Moon',
    'Nonbasic lands are Mountains.',
    'Enchantment', 'Stax'],
  ['Stasis',
    'Players skip their untap steps.',
    'Enchantment', 'Stax'],

  // ── Anthem ───────────────────────────────────────────────────────────────
  ['Glorious Anthem',
    'Creatures you control get +1/+1.',
    'Enchantment', 'Anthem'],
  ['Honor of the Pure',
    'White creatures you control get +1/+1.',
    'Enchantment', 'Anthem'],
  ['Lord of Atlantis (tribal anthem creature)',
    'Other Merfolk creatures get +1/+1 and have islandwalk.',
    'Creature — Merfolk', 'Anthem'],
  ['Giant Growth (combat trick stays Instant)',
    'Target creature gets +3/+3 until end of turn.',
    'Instant', 'Instant'],

  // ── +1/+1 Counters ───────────────────────────────────────────────────────
  ['Hardened Scales',
    'If you would put one or more +1/+1 counters on a permanent you control, put that many plus one +1/+1 counters on it instead.',
    'Enchantment', '+1/+1 Counters'],
  ['Cathars\' Crusade',
    'Whenever a creature enters the battlefield under your control, put a +1/+1 counter on each creature you control.',
    'Enchantment', '+1/+1 Counters'],
  ['Contagion Engine (proliferate)',
    '{4}, {T}: Each player who lost life this turn loses 2 life. Proliferate, then proliferate again.',
    'Artifact', '+1/+1 Counters'],

  // ── Landfall (must win over Ramp / Tokens / Card Draw) ──────────────────
  ['Lotus Cobra (landfall, not ramp)',
    'Landfall — Whenever a land you control enters the battlefield, add one mana of any color.',
    'Creature — Snake', 'Landfall'],
  ['Avenger of Zendikar (landfall, not tokens)',
    'When Avenger of Zendikar enters the battlefield, create six 0/1 green Plant creature tokens. Landfall — Whenever a land you control enters the battlefield, put a +1/+1 counter on each Plant creature you control.',
    'Creature — Elemental', 'Landfall'],
  ['Tireless Tracker (land-enter trigger, no "Landfall" keyword)',
    'Whenever you sacrifice a Clue, put a +1/+1 counter on Tireless Tracker. Whenever a land enters the battlefield under your control, investigate.',
    'Creature — Human Scout', 'Landfall'],

  // ── Sacrifice (must win over Ramp for sac-mana outlets, but lose to Tutor) ─
  ['Viscera Seer (sac outlet)',
    'Sacrifice a creature: Scry 1.',
    'Creature — Vampire Wizard', 'Sacrifice'],
  ['Phyrexian Altar (sac, not Ramp)',
    'Sacrifice a creature: Add one mana of any color.',
    'Artifact', 'Sacrifice'],
  ["Ashnod's Altar (sac, not Ramp)",
    'Sacrifice a creature: Add {C}{C}.',
    'Artifact', 'Sacrifice'],
  ['Dictate of Erebos (death trigger)',
    'Whenever a creature you control dies, each opponent sacrifices a creature.',
    'Enchantment', 'Sacrifice'],
  ['Birthing Pod (Tutor beats Sacrifice)',
    '{1}{G/P}, {T}, Sacrifice a creature: Search your library for a creature card with mana value equal to 1 plus the sacrificed creature\'s mana value, put it onto the battlefield, then shuffle.',
    'Artifact', 'Tutor'],

  // ── Blink / Flicker (before Removal so "exile target creature" stays Blink) ─
  ['Cloudshift',
    'Exile target creature you control, then return that card to the battlefield under your control.',
    'Instant', 'Blink'],
  ['Conjurer\'s Closet',
    'At the beginning of your end step, you may exile target creature you control, then return that card to the battlefield under your control.',
    'Artifact', 'Blink'],
  ['Eldrazi Displacer',
    '{2}{C}: Exile another target creature, then return it to the battlefield tapped under its owner\'s control.',
    'Creature — Eldrazi', 'Blink'],

  // ── Lifegain (after Removal/Burn so Lightning Helix stays Removal) ────────
  ['Soul Warden',
    'Whenever another creature enters the battlefield, you gain 1 life.',
    'Creature — Human Cleric', 'Lifegain'],
  ['Bishop of Wings (lifegain wins over Tokens)',
    'Whenever an Angel enters the battlefield under your control, you gain 4 life. Whenever Bishop of Wings dies, create a 4/4 white Angel creature token with flying.',
    'Creature — Human Cleric', 'Lifegain'],
  ['Trelasarra, Moon Dancer (lifegain trigger)',
    'Whenever you gain life, scry 1, then put a +1/+1 counter on Trelasarra, Moon Dancer.',
    'Creature — Human Soldier', 'Lifegain'],

  // ── Copy ─────────────────────────────────────────────────────────────────
  ['Twincast',
    'Copy target instant or sorcery spell. You may choose new targets for the copy.',
    'Instant', 'Copy'],
  ['Twinflame (token copy, not Tokens)',
    'Create a token that\'s a copy of target creature you control. That token has haste. Exile it at the beginning of the next end step.',
    'Sorcery', 'Copy'],
  ['Clone',
    'You may have Clone enter the battlefield as a copy of any creature on the battlefield.',
    'Creature — Shapeshifter', 'Copy'],
  ['Pyromancer\'s Goggles',
    '{T}: Add {R}. Whenever you cast an instant or sorcery spell with {R} in its cost, you may copy that spell. You may choose new targets for the copy.',
    'Legendary Artifact', 'Copy'],

  // ── Evasion (after Protection so Whispersilk Cloak stays Protection) ──────
  ['Aqueous Form',
    'Enchanted creature can\'t be blocked. Whenever enchanted creature attacks, scry 1.',
    'Enchantment — Aura', 'Evasion'],
  ['Levitation (grant flying)',
    'Creatures you control have flying.',
    'Enchantment', 'Evasion'],
  ['Whispersilk Cloak (Protection wins via shroud)',
    'Equipped creature has shroud and can\'t be blocked.',
    'Artifact — Equipment', 'Protection'],

  // ── Real Scryfall oracle text from cards reported as misfiled ───────────
  // (post-2024 wording: "enters" replaces "enters the battlefield")
  ['Avenger of Zendikar (current Scryfall text)',
    'When this creature enters, create six 0/1 green Plant creature tokens.\nLandfall — Whenever a land you control enters, put a +1/+1 counter on each Plant creature you control.',
    'Creature — Elemental', 'Landfall'],
  ['Omnath, Locus of Rage (current Scryfall text)',
    'Landfall — Whenever a land enters the battlefield under your control, create a 5/5 red and green Elemental creature token.\nWhenever Omnath, Locus of Rage or another Elemental you control dies, Omnath deals 3 damage to any target.',
    'Legendary Creature — Elemental', 'Landfall'],
  ['Greenwarden of Murasa (post-2024 enters wording)',
    'When this creature enters, you may return target card from your graveyard to your hand.\nWhen Greenwarden of Murasa dies, you may exile it. If you do, return another target card from your graveyard to your hand.',
    'Creature — Elemental', 'Graveyard'],
  ['Ingot Chewer (artifact removal)',
    'Evoke {R}\nWhen this creature enters, destroy target artifact.',
    'Creature — Elemental', 'Removal'],
  ['Foundation Breaker (artifact/enchantment removal)',
    'Evoke {2}{G}\nWhen this creature enters, you may destroy target artifact or enchantment.',
    'Creature — Elemental Druid', 'Removal'],
  ['Incandescent Soulstoke (Elemental anthem)',
    'Other Elemental creatures you control get +1/+0.\n{1}{R}, {T}: Put an Elemental creature card with mana value 3 or less from your hand onto the battlefield. That creature gains haste. Sacrifice it at the beginning of the next end step.',
    'Creature — Elemental Shaman', 'Anthem'],
  ['Cavalier of Thorns (library land fetch, not from hand)',
    'Reach.\nWhen this creature enters, reveal the top five cards of your library. Put all land cards among them onto the battlefield tapped and the rest on the bottom of your library in a random order.\nWhen this creature dies, exile it, then you may put another target card from your graveyard on top of your library.',
    'Creature — Elemental Knight', 'Ramp'],
  ['Muldrotha, the Gravetide (play from graveyard)',
    'Each turn, you may play a permanent card of each permanent type from your graveyard.',
    'Legendary Creature — Elemental Avatar', 'Graveyard'],
  ['Lurrus of the Dream-Den (cast from graveyard)',
    'Companion — Each permanent card in your starting deck has mana value 2 or less.\nDuring each of your turns, you may cast one permanent spell with mana value 2 or less from your graveyard.',
    'Legendary Creature — Cat Nightmare', 'Graveyard'],
  ['Sunderflock (mass bounce wins over cost reduction)',
    "This spell costs {X} less to cast, where X is the greatest mana value among Elementals you control.\nFlying\nWhen this creature enters, if you cast it, return all non-Elemental creatures to their owners' hands.",
    'Creature — Elemental', 'Board Wipe'],
  ['Incandescent Soulstoke (anthem despite "until end of turn" in activated ability)',
    'Other Elemental creatures you control get +1/+1.\n{1}{R}, {T}: You may put an Elemental creature card from your hand onto the battlefield. That creature gains haste until end of turn. Sacrifice it at the beginning of the next end step.',
    'Creature — Elemental Shaman', 'Anthem'],
  ['Risen Reef (land-card → battlefield ramp)',
    "Whenever this creature or another Elemental you control enters, look at the top card of your library. If it's a land card, you may put it onto the battlefield tapped. If you don't put the card onto the battlefield, put it into your hand.",
    'Creature — Elemental', 'Ramp'],
  ['Interdisciplinary Mascot (put-into-hand card draw)',
    'Convoke\nWard {3}\nWhen this creature enters, look at the top four cards of your library. Put one of them into your hand and the rest on the bottom of your library in a random order.',
    'Creature — Elemental Fractal', 'Card Draw'],
  ['Champion of the Path (variable-amount burn)',
    "As an additional cost to cast this spell, behold an Elemental and exile it.\nWhenever another Elemental you control enters, it deals damage equal to its power to each opponent.\nWhen this creature leaves the battlefield, return the exiled card to its owner's hand.",
    'Creature — Elemental Sorcerer', 'Burn'],
  ['Smokebraider (ramp dork)',
    '{T}: Add two mana in any combination of colors. Spend this mana only to cast Elemental spells or activate abilities of Elementals.',
    'Creature — Elemental', 'Ramp'],

  // ── Doublers (trigger / token / counter / draw doublers) ────────────────
  ['Panharmonicon (ETB trigger doubler)',
    'If an artifact or creature entering the battlefield causes a triggered ability of a permanent you control to trigger, that ability triggers an additional time.',
    'Artifact', 'Doublers'],
  ['Yarok, the Desecrated (permanent-ETB trigger doubler)',
    'Deathtouch, lifelink\nIf a permanent entering causes a triggered ability of a permanent you control to trigger, that ability triggers an additional time.',
    'Legendary Creature — Elemental Horror', 'Doublers'],
  ['Twinflame Travelers (Elemental trigger doubler)',
    'Flying\nIf a triggered ability of another Elemental you control triggers, it triggers an additional time.',
    'Creature — Elemental Sorcerer', 'Doublers'],
  ['Doubling Season (token + counter doubler beats Tokens)',
    'If an effect would create one or more tokens under your control, that effect creates twice that many of those tokens instead.\nIf an effect would put one or more counters on a permanent you control, that effect puts twice that many of those counters on that permanent instead.',
    'Enchantment', 'Doublers'],
  ['Parallel Lives (token doubler)',
    'If an effect would create one or more tokens under your control, it creates twice that many of those tokens instead.',
    'Enchantment', 'Doublers'],
  ['Anointed Procession (token doubler)',
    'If an effect would create one or more tokens under your control, it creates twice that many of those tokens instead.',
    'Enchantment', 'Doublers'],
  ['Strionic Resonator (trigger doubler via copy)',
    '{2}, {T}: Copy target triggered ability you control. You may choose new targets for the copy.',
    'Artifact', 'Doublers'],
  ["Teferi's Ageless Insight (draw doubler)",
    'If you would draw a card except the first one you draw in each of your draw steps, instead draw two cards.',
    'Legendary Enchantment', 'Doublers'],
  // Regression: a single-token creator should still be Tokens, not Doublers.
  ['Lingering Souls stays Tokens (single token, no doubling)',
    'Create two 1/1 white and black Spirit creature tokens with flying. Flashback {1}{B}.',
    'Sorcery', 'Tokens'],

  // ── Cheat into play ──────────────────────────────────────────────────────
  ['Sneak Attack',
    '{R}: You may put a creature card from your hand onto the battlefield. That creature gains haste. Sacrifice the creature at the beginning of the next end step.',
    'Enchantment', 'Cheat'],
  ['Through the Breach',
    'Splice onto Arcane {2}{R}{R}\nYou may put a creature card from your hand onto the battlefield. Sacrifice it at the beginning of the next end step.',
    'Instant — Arcane', 'Cheat'],
  ['Show and Tell (multi-type hand cheat)',
    'Each player may put an artifact, creature, enchantment, or land card from their hand onto the battlefield.',
    'Sorcery', 'Cheat'],
  ['Quicksilver Amulet',
    "{4}, {T}: You may put a creature card from your hand onto the battlefield.",
    'Artifact', 'Cheat'],
  ['Elvish Piper',
    '{G}, {T}: You may put a creature card from your hand onto the battlefield.',
    'Creature — Elf', 'Cheat'],
  // Regression: Soulstoke has a cheat clause but its anthem is the iconic role.
  ['Soulstoke stays Anthem despite cheat clause',
    'Other Elemental creatures you control get +1/+1.\n{1}{R}, {T}: You may put an Elemental creature card from your hand onto the battlefield. That creature gains haste until end of turn. Sacrifice it at the beginning of the next end step.',
    'Creature — Elemental Shaman', 'Anthem'],
  // Regression: a basic-land hand play should stay Ramp, not get caught by Cheat.
  ['Sakura-Tribe Scout stays Ramp',
    '{T}: You may put a land card from your hand onto the battlefield.',
    'Creature — Snake Scout', 'Ramp'],
  // Cascade is the library-side equivalent of cheat-into-play.
  ['Maelstrom Wanderer (cascade x2)',
    'Creatures you control have haste.\nCascade, cascade (When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost. Put the exiled cards on the bottom in a random order. Then do it again.)',
    'Legendary Creature — Elemental', 'Cheat'],
  ['Bloodbraid Elf (cascade)',
    'Cascade\nHaste',
    'Creature — Elf Berserker', 'Cheat'],
  ['Imoti, Celebrant of Bounty (cascade enabler)',
    'Spells you cast with mana value 6 or greater have cascade.',
    'Legendary Creature — Human Druid', 'Cheat'],
  // Regression: cascade cards whose primary effect is removal still resolve
  // as Removal because that rule fires earlier in the ladder.
  ['Bituminous Blast stays Removal despite cascade',
    'Destroy target creature.\nCascade',
    'Instant', 'Removal'],

  // ── Cards previously misfiled to the type-line fallback ────────────────
  ['High Tide ("adds {U}" trigger → Ramp)',
    'Until end of turn, whenever a player taps an Island for mana, that player adds {U}.',
    'Instant', 'Ramp'],
  ['Time Stretch ("take two extra turns")',
    'Take two extra turns after this one.',
    'Sorcery', 'Extra Turns'],
  ['Curse of the Swine ("Exile X target creatures")',
    'Exile X target creatures. For each creature exiled this way, its controller creates a 2/2 green Boar creature token.',
    'Sorcery', 'Removal'],
  ['Chaos Warp (shuffle target permanent into library)',
    "The owner of target permanent shuffles it into their library, then reveals the top card of their library. If it's a permanent card, they put it onto the battlefield.",
    'Instant', 'Removal'],
  ['Comet Storm (damage divided among targets → Burn)',
    'Multikicker {1}{R}\nComet Storm deals X damage divided as you choose among any number of targets.',
    'Instant', 'Burn'],
  ['Deflecting Swat (choose new targets → Protection)',
    'If you control a commander, you may cast this spell without paying its mana cost. You may choose new targets for target spell or ability.',
    'Instant', 'Protection'],
  ['Display of Power (gain control of target → Combo)',
    'Until end of turn, you gain control of target permanent and untap it. It gains haste.',
    'Instant', 'Combo'],
  ['City on Fire (damage doubler → Doublers)',
    'Each spell, ability, and source you control deals double damage to permanents and players.',
    'Enchantment', 'Doublers'],
  ['Furnace of Rath (damage doubler → Doublers)',
    'If a source would deal damage to a permanent or player, it deals double that damage to that permanent or player instead.',
    'Enchantment', 'Doublers'],
  ['Threaten (steal until end of turn → Combo)',
    'Untap target creature an opponent controls and gain control of it until end of turn. It gains haste.',
    'Sorcery', 'Combo'],
  // Regression: self-recursion clauses ("shuffle it into its owner's library")
  // must NOT mis-fire as Removal. The "owner of target permanent" anchor on the
  // shuffle rule prevents that. Worldspine Wurm itself resolves as Tokens via
  // the earlier token-creation rule (its iconic effect), which is correct.
  ['Worldspine Wurm self-shuffle does not become Removal',
    "Trample\nWhen Worldspine Wurm is put into a graveyard from anywhere, shuffle it into its owner's library.",
    'Creature — Wurm', 'Creature'],

  // ── Type fallback (no functional role detected) ──────────────────────────
  ['Tarmogoyf (vanilla-ish creature)',
    'Tarmogoyf\'s power is equal to the number of card types among cards in all graveyards and its toughness is equal to that number plus 1.',
    'Creature — Lhurgoyf', 'Creature'],
  ['Goblin Guide (haste-only creature)',
    'Haste. Whenever Goblin Guide attacks, defending player reveals the top card of their library. If it\'s a land card, that player puts it into their hand.',
    'Creature — Goblin Scout', 'Creature'],
  ['Forest (basic land)',
    '({T}: Add {G}.)',
    'Basic Land — Forest', 'Land'],
]

describe('getCardCategory', () => {
  for (const [name, oracle, typeLine, expected] of cases) {
    it(`classifies ${name} as ${expected}`, () => {
      expect(getCardCategory(oracle, typeLine)).toBe(expected)
    })
  }

  it('handles missing oracle/type gracefully', () => {
    expect(getCardCategory()).toBe('Other')
    expect(getCardCategory('', '')).toBe('Other')
    expect(getCardCategory(null, null)).toBe('Other')
  })
})
