/**
 * DatabaseService — on-device card hash store
 *
 * The card fingerprint database ships as a few static binary chunks
 * ("hash pack", see hashPack.js) generated by scripts/generate-card-hashes.js:
 *
 *   cold start   one same-origin fetch per chunk (~2–3 MB each) instead of
 *                the old ~107 paginated PostgREST requests (~35 MB JSON)
 *   warm start   chunks load from IndexedDB as single ArrayBuffer blobs
 *                instead of 106k object records
 *   native       chunks are bundled in the APK (Capacitor serves public/),
 *                so first run is offline; newer chunks are fetched from
 *                deckloom.app when the manifest advertises them
 *   matching     the hash-match worker receives the raw buffers (memcpy
 *                clone, no object-graph serialization) and owns the LSH
 *                band index; the main thread keeps a lightweight fallback
 *                matcher over the same buffers for when Workers fail
 *
 * Scanning can start as soon as the first chunk is in (chunk 0 holds the
 * newest sets); the rest streams in the background.
 */

import { Capacitor } from '@capacitor/core'
import { HashPackStore } from './hashPack'
import { createMatcher } from './matchCore'
import { buildNameIndex, matchTitle } from './nameMatch'
import { loadManifest, loadChunkBuffer, prunePackChunks, MANIFEST_META_KEY } from './packLoader'
import { clearPackChunks, getMeta, setMeta } from '../lib/db'
import { hammingDistance } from './hashCore'

export { hammingDistance }

const LEGACY_CLEANUP_KEY = 'scanner_pack_migrated_v1'

class DatabaseService {
  _store       = new HashPackStore()
  _matcher     = createMatcher(this._store)
  _initialized = false
  _syncing     = false
  _syncPromise = null
  _fullyLoaded = false
  _packLoading = false
  _loadPromise = Promise.resolve()
  _initPromise = null
  _onProgress  = null
  _matchWorker = null
  _workerSeq = 1
  _workerPending = new Map()
  _workerFailed = false
  _status = {
    loadedCount: 0,
    totalCount: 0,
    progress: 0,
    phase: 'idle',
    source: 'none',
  }

  _emitProgress(patch = {}) {
    this._status = { ...this._status, ...patch }
    const total = this._status.totalCount || this._status.loadedCount || 0
    this._status.progress = total > 0
      ? Math.max(0, Math.min(100, Math.round((this._status.loadedCount / total) * 100)))
      : 0
    this._onProgress?.({ ...this._status })
  }

  _emitSnapshot() {
    this._emitProgress({
      loadedCount: this._store.count,
      totalCount: this._status.totalCount || this._store.count,
      phase: this._fullyLoaded ? 'ready' : this._status.phase,
    })
  }

  async init(onProgress) {
    if (onProgress) this._onProgress = onProgress   // always wire latest caller into ongoing stream
    if (this._initPromise) {
      await this._initPromise
      this._emitSnapshot()
      return this
    }
    if (this._initialized) {
      // Re-init when in-memory data is significantly incomplete (an earlier
      // load lost chunks to network errors) — unless a load is still running.
      const total = this._status.totalCount
      const incomplete = total > 0 && this._store.count < Math.floor(total * 0.98)
      if (!incomplete || this._packLoading) {
        this._emitSnapshot()
        return this
      }
      this._initialized = false
    }

    this._initPromise = (async () => {
      await this._loadPack()
      this._initialized = true
      this._legacyCleanup()
      return this
    })()

    try {
      return await this._initPromise
    } finally {
      this._initPromise = null
    }
  }

  /**
   * Load manifest + chunks. Resolves once the FIRST chunk is available (or the
   * load failed outright); the remaining chunks continue in the background via
   * _loadPromise so scanning can start against a partial database.
   */
  async _loadPack() {
    this._packLoading = true
    this._fullyLoaded = false
    this._store = new HashPackStore()
    this._matcher = createMatcher(this._store)
    this._postMatchWorker('reset', {}).catch(() => {})

    this._emitProgress({ loadedCount: 0, totalCount: 0, phase: 'connecting', source: 'none' })

    const resolved = await loadManifest().catch(() => null)
    if (!resolved) {
      this._packLoading = false
      this._loadPromise = Promise.resolve(0)
      this._emitProgress({ loadedCount: 0, phase: 'network retry needed', source: 'network' })
      return
    }

    const { manifest } = resolved
    const totalCount = manifest.totalCount ||
      manifest.chunks.reduce((sum, c) => sum + (c.count || 0), 0)
    this._emitProgress({ loadedCount: 0, totalCount, phase: 'checking cache', source: 'idb' })

    let resolveFirst
    const firstChunk = new Promise(r => { resolveFirst = r })

    const run = async () => {
      let allLoaded = true
      for (const chunk of manifest.chunks) {
        const cardsBefore = this._store.count
        try {
          const { buf, fromCache } = await loadChunkBuffer(chunk, {
            hashVersion: manifest.hashVersion,
            onBytes: (received, total) => {
              const frac = total > 0 ? Math.min(1, received / total) : 0
              this._emitProgress({
                loadedCount: cardsBefore + Math.round(chunk.count * frac),
                totalCount,
                phase: 'downloading hashes',
                source: 'network',
              })
            },
          })
          this._store.appendChunkBuffer(buf)
          this._matcher.invalidate()
          // No transfer list on purpose: the main-thread store keeps views over
          // `buf`; the worker gets its own copy (ArrayBuffer clone = memcpy).
          this._postMatchWorker('appendChunk', { buffer: buf }).catch(() => {})
          this._emitProgress({
            loadedCount: this._store.count,
            totalCount,
            phase: 'loading hashes',
            source: fromCache ? 'idb cache' : 'network',
          })
          resolveFirst()
        } catch (e) {
          allLoaded = false
          console.warn(`[DatabaseService] chunk load failed (${chunk.file}):`, e?.message ?? e)
        }
      }
      resolveFirst()   // in case every chunk failed
      await prunePackChunks(manifest)
      this._fullyLoaded = allLoaded
      this._emitProgress({
        loadedCount: this._store.count,
        totalCount,
        phase: allLoaded ? 'ready' : 'network retry needed',
        source: this._status.source,
      })
      return this._store.count
    }

    this._loadPromise = run().finally(() => { this._packLoading = false })
    await firstChunk
  }

  /** Force a fresh download (clears cached chunks + manifest first). */
  async sync(onProgress) {
    if (onProgress) this._onProgress = onProgress
    if (this._syncPromise) return this._syncPromise
    this._syncPromise = (async () => {
      this._syncing = true
      try {
        await this._loadPromise.catch(() => {})
        await clearPackChunks().catch(() => {})
        await setMeta(MANIFEST_META_KEY, null).catch(() => {})
        await this._loadPack()
        await this._loadPromise
      } finally {
        this._syncing = false
      }
    })().finally(() => { this._syncPromise = null })
    return this._syncPromise
  }

  /**
   * One-time cleanup of the pre-pack storage: legacy meta keys and, on
   * native, the old SQLite hash database (~40 MB). Best-effort, async.
   */
  _legacyCleanup() {
    ;(async () => {
      if (await getMeta(LEGACY_CLEANUP_KEY).catch(() => 1)) return
      await setMeta(LEGACY_CLEANUP_KEY, 1).catch(() => {})
      for (const key of ['scanner_cache_version', 'scanner_hash_total_count', 'scanner_sqlite_count']) {
        await setMeta(key, null).catch(() => {})
      }
      if (Capacitor.isNativePlatform()) {
        try {
          const mod = await import('@capacitor-community/sqlite')
          const sqlite = new mod.SQLiteConnection(mod.CapacitorSQLite)
          if ((await sqlite.isDatabase('arcanevault_hashes'))?.result) {
            const isConn = (await sqlite.isConnection('arcanevault_hashes', false)).result
            const db = isConn
              ? await sqlite.retrieveConnection('arcanevault_hashes', false)
              : await sqlite.createConnection('arcanevault_hashes', false, 'no-encryption', 1, false)
            await db.open()
            await db.delete()
          }
        } catch { /* old DB stays orphaned — harmless */ }
      }
    })().catch(() => {})
  }

  // ── Match worker ───────────────────────────────────────────────────────────

  _ensureMatchWorker() {
    if (this._workerFailed || typeof Worker === 'undefined') return null
    if (this._matchWorker) return this._matchWorker
    try {
      this._matchWorker = new Worker(new URL('./hashMatchWorker.js', import.meta.url), { type: 'module' })
      this._matchWorker.onmessage = event => {
        const { id, ok, result, error } = event.data || {}
        const pending = this._workerPending.get(id)
        if (!pending) return
        this._workerPending.delete(id)
        if (ok) pending.resolve(result)
        else pending.reject(new Error(error || 'Hash match worker failed'))
      }
      this._matchWorker.onerror = error => {
        this._workerFailed = true
        for (const pending of this._workerPending.values()) {
          pending.reject(new Error(error?.message || 'Hash match worker failed'))
        }
        this._workerPending.clear()
        this._matchWorker?.terminate()
        this._matchWorker = null
      }
      // A fresh worker starts empty — replay chunks already held by the store.
      for (const chunk of this._store.chunks) {
        this._postToWorkerRaw('appendChunk', { buffer: chunk.buffer }).catch(() => {})
      }
      return this._matchWorker
    } catch {
      this._workerFailed = true
      return null
    }
  }

  _postToWorkerRaw(type, payload) {
    const worker = this._matchWorker
    if (!worker) return Promise.reject(new Error('Hash match worker unavailable'))
    const id = this._workerSeq++
    return new Promise((resolve, reject) => {
      this._workerPending.set(id, { resolve, reject })
      worker.postMessage({ id, type, payload })
    })
  }

  _postMatchWorker(type, payload) {
    const worker = this._ensureMatchWorker()
    if (!worker) return Promise.reject(new Error('Hash match worker unavailable'))
    return this._postToWorkerRaw(type, payload)
  }

  // ── Match API ──────────────────────────────────────────────────────────────

  findMatch(hash, threshold = 20) {
    const best = this.findBest(hash)
    if (!best) return null
    return best.distance <= threshold ? best : null
  }

  findBest(hash) {
    const [best] = this.findBestTwo(hash)
    return best
  }

  findBestTwo(hash) {
    const { best, second } = this.findBestTwoWithStats(hash)
    return [best, second]
  }

  // Synchronous main-thread matcher — fallback path when the worker is
  // unavailable. colorHash/fullHash: optional Uint32Array(8); combined
  // distance weighting lives in matchCore.
  findBestTwoWithStats(hash, colorHash = null, fullHash = null, opts = {}) {
    return this._matcher.match(hash, colorHash, fullHash, opts)
  }

  async findBestTwoWithStatsAsync(hash, colorHash = null, fullHash = null, opts = {}) {
    if (!this._store.count) {
      return { best: null, second: null, candidateCount: 0, totalCount: 0 }
    }
    try {
      return await this._postMatchWorker('match', {
        hash: Array.from(hash),
        colorHash: colorHash ? Array.from(colorHash) : null,
        fullHash: fullHash ? Array.from(fullHash) : null,
        opts: { ...opts, allowedSets: opts.allowedSets?.size ? [...opts.allowedSets] : null },
      })
    } catch {
      return this._matcher.match(hash, colorHash, fullHash, opts)
    }
  }

  // Batch multiple hash variants (standard/foil/dark) into a single worker round-trip.
  // queries: Array<{ hash: number[] | Uint32Array, label: string }>
  async findBestTwoWithStatsAsyncAll(queries, colorHash = null, fullHash = null, opts = {}) {
    if (!this._store.count) {
      return { best: null, second: null, candidateCount: 0, totalCount: 0, bestLabel: null }
    }
    try {
      return await this._postMatchWorker('matchAll', {
        queries: queries.map(({ hash, label }) => ({ hash: hash ? Array.from(hash) : null, label })),
        colorHash: colorHash ? Array.from(colorHash) : null,
        fullHash: fullHash ? Array.from(fullHash) : null,
        opts: { ...opts, allowedSets: opts.allowedSets?.size ? [...opts.allowedSets] : null },
      })
    } catch {
      const normalized = queries.map(({ hash, label }) => ({
        hash: hash ? new Uint32Array(hash) : null,
        label,
      }))
      return this._matcher.matchAll(normalized, colorHash, fullHash, opts)
    }
  }

  /**
   * Exact-print lookup by OCR'd set code + collector number.
   * Returns a public card object ({ id, name, setCode, collNum, imageUri })
   * or null. Runs on the main-thread store copy (no worker round-trip).
   */
  lookupPrint(setCode, collNum) {
    const idx = this._store.findByPrint(setCode, collNum)
    return idx >= 0 ? this._store.getCardPublic(idx, 0) : null
  }

  /** Set codes present in the loaded pack (OCR set-candidate validation). */
  get knownSets() { return this._store.allSets() }

  /**
   * Identify a card from OCR'd title-bar text (name-rescue path). Returns
   * { card, name, distance } or null when no name matches uniquely enough.
   * `allowedSets` (lowercase Set) restricts the returned printing when the
   * user has locked sets; printings are newest-first, so the first index is
   * the newest printing of that name.
   */
  identifyByTitle(rawText, { allowedSets = null } = {}) {
    if (!this._store.count) return null
    if (!this._nameIndex || this._nameIndexCount !== this._store.count) {
      const entries = []
      const decoder = new TextDecoder()
      let globalIdx = 0
      for (const chunk of this._store.chunks) {
        for (let i = 0; i < chunk.count; i++, globalIdx++) {
          const [name, , flavorName] = HashPackStore.rowMeta(chunk, i, decoder)
          entries.push({ name, idx: globalIdx })
          // Crossover cards (Marvel, Godzilla…) print the FLAVOR name in the
          // title bar — index it too so the title rescue can read them.
          if (flavorName) entries.push({ name: flavorName, idx: globalIdx })
        }
      }
      this._nameIndex = buildNameIndex(entries)
      this._nameIndexCount = this._store.count
    }

    const hit = matchTitle(rawText, this._nameIndex)
    if (!hit) return null

    let idx = hit.idxs[0]
    if (allowedSets?.size) {
      idx = hit.idxs.find(i => {
        const loc = this._store.locate(i)
        return loc && allowedSets.has(loc.chunk.sets[loc.chunk.setIdx[loc.local]])
      })
      if (idx === undefined) return null   // locked out — no printing in the allowed sets
    }
    return { card: this._store.getCardPublic(idx, 0), name: hit.name, distance: hit.distance }
  }

  get cardCount()       { return this._store.count }
  get isReady()         { return this._initialized }
  get isSyncing()       { return this._syncing }
  get isFullyLoaded()   { return this._fullyLoaded }
  get status()          { return this._status }
  waitUntilFullyLoaded() { return this._loadPromise }
}

export const databaseService = new DatabaseService()
